apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: spire-agent
  namespace: spire-system
  labels:
    app: spire-agent
spec:
  selector:
    matchLabels:
      app: spire-agent
  template:
    metadata:
      labels:
        app: spire-agent
    spec:
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: spire-agent
      initContainers:
        - name: init
          image: busybox:1.35
          command: ['sh', '-c']
          args:
            - |
              echo "Waiting for SPIRE server to be ready..."
              # The server address will be set by the setup script dynamically
              # This init container just waits a reasonable time for the server to start
              sleep 30
              echo "SPIRE server should be ready!"
      containers:
        - name: spire-agent
          image: ghcr.io/spiffe/spire-agent:1.12.4
          args:
            - -config
            - /run/spire/config/agent.conf
          ports:
            - containerPort: 8080
              name: health
            - containerPort: 9988
              name: metrics
          volumeMounts:
            - name: spire-config
              mountPath: /run/spire/config
              readOnly: true
            - name: spire-bundle
              mountPath: /run/spire/bundle
              readOnly: true
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: false
            - name: spire-agent-token
              mountPath: /var/run/secrets/tokens
              readOnly: true
          livenessProbe:
            httpGet:
              path: /live
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: spire-config
          configMap:
            name: spire-agent-config
        - name: spire-bundle
          configMap:
            name: spire-bundle
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: DirectoryOrCreate
        - name: spire-agent-token
          projected:
            sources:
            - serviceAccountToken:
                path: spire-agent
                expirationSeconds: 3600
                audience: spire-server