apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: workload
  labels:
    app: inventory-service
    service: inventory-management
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
        service: inventory-management
        tier: backend
    spec:
      serviceAccountName: inventory-service
      containers:
      - name: inventory-service
        image: python:3.9-slim
        command: ["python", "-m", "http.server", "8082"]
        ports:
        - containerPort: 8082
          name: http
        volumeMounts:
        - name: spire-agent-socket
          mountPath: /run/spire/sockets
          readOnly: true
        env:
        - name: SPIFFE_ENDPOINT_SOCKET
          value: "unix:///run/spire/sockets/agent.sock"
        - name: SERVICE_NAME
          value: "inventory-service"
        - name: SERVICE_PORT
          value: "8082"
        - name: REDIS_URL
          value: "redis://inventory-cache:6379"
        - name: DATABASE_URL
          value: "postgresql://inventory:inventory@inventory-db:5432/inventory"
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
      volumes:
      - name: spire-agent-socket
        hostPath:
          path: /run/spire/sockets
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: workload
  labels:
    app: inventory-service
    service: inventory-management
spec:
  selector:
    app: inventory-service
  ports:
  - port: 8082
    targetPort: 8082
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory-service
  namespace: workload
  labels:
    app: inventory-service
    service: inventory-management