apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: spire-workload
  labels:
    app: inventory-service
    service: inventory-management
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
        service: inventory-management
        tier: backend
    spec:
      serviceAccountName: inventory-service
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 3000
        fsGroup: 2000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: inventory-service
        image: python:3.9-slim
        command: ["python", "-m", "http.server", "8082"]
        ports:
        - containerPort: 8082
          name: http
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1001
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - name: spire-agent-socket
          mountPath: /run/spire/sockets
          readOnly: true
        env:
        - name: SPIFFE_ENDPOINT_SOCKET
          value: "unix:///run/spire/sockets/agent.sock"
        - name: SERVICE_NAME
          value: "inventory-service"
        - name: SERVICE_PORT
          value: "8082"
        - name: REDIS_URL
          value: "redis://inventory-cache:6379"
        - name: DATABASE_URL
          value: "mysql://inventory:inventory@inventory-db:3306/inventory"
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
      volumes:
      - name: spire-agent-socket
        hostPath:
          path: /run/spire/sockets
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: spire-workload
  labels:
    app: inventory-service
    service: inventory-management
spec:
  selector:
    app: inventory-service
  ports:
  - port: 8082
    targetPort: 8082
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory-service
  namespace: spire-workload
  labels:
    app: inventory-service
    service: inventory-management