apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2
  namespace: workload
  labels:
    app: service2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service2
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
      - name: service2
        image: httpd:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: spire-agent-socket
          mountPath: /run/spire/sockets
          readOnly: true
        env:
        - name: SPIFFE_ENDPOINT_SOCKET
          value: "unix:///run/spire/sockets/agent.sock"
      volumes:
      - name: spire-agent-socket
        hostPath:
          path: /run/spire/sockets
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: service2
  namespace: workload
spec:
  selector:
    app: service2
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP