apiVersion: v1
kind: Namespace
metadata:
  name: spire-system
  labels:
    name: spire-system
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted