apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: spire-workload
  labels:
    app: user-service
    service: user-management
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
        service: user-management
        tier: backend
    spec:
      serviceAccountName: user-service
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 3000
        fsGroup: 2000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: user-service
        image: alpine/curl:latest
        command: ["sh", "-c", "while true; do echo 'User Service running - SPIFFE enabled'; sleep 300; done"]
        ports:
        - containerPort: 8080
          name: http
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1001
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - name: spire-agent-socket
          mountPath: /run/spire/sockets
          readOnly: true
        env:
        - name: SPIFFE_ENDPOINT_SOCKET
          value: "unix:///run/spire/sockets/agent.sock"
        - name: SERVICE_NAME
          value: "user-service"
        - name: SERVICE_PORT
          value: "8080"
        - name: DATABASE_URL
          value: "mysql://users:users@user-db:3306/users"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
      volumes:
      - name: spire-agent-socket
        hostPath:
          path: /run/spire/sockets
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: spire-workload
  labels:
    app: user-service
    service: user-management
spec:
  selector:
    app: user-service
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-service
  namespace: spire-workload
  labels:
    app: user-service
    service: user-management