# Jekyll Configuration for SPIRE Local Development Environment

title: SPIRE Local Development Environment
description: Learn and experiment with SPIFFE/SPIRE on your local machine - perfect for testing, development, and understanding zero-trust identity concepts
author: SPIRE Development Community
url: "https://jfiser247.github.io"
baseurl: "/spire-dev"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Jekyll plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - k8s/
  - helm-charts/
  - examples/
  - scripts/
  - web/
  - _site/
  - .git/
  - .gitignore
  - reproducibility-test-results.log

# Include files
include:
  - _pages

# Collections
collections:
  pages:
    output: true
    permalink: /:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "SPIRE Development Community"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Navigation
navigation:
  - title: "🏠 Home"
    url: /
  - title: "🚀 Getting Started"
    subpages:
      - title: "Fresh Install Setup"
        url: /fresh-install-guide/
      - title: "Quick Start Integration"
        url: /quick-start-workload-integration/
      - title: "Troubleshooting Setup"
        url: /troubleshooting/
  - title: "🎓 Learning SPIRE"
    subpages:
      - title: "SPIFFE Service Integration"
        url: /spiffe-service-integration/
      - title: "Workload Integration Guide"
        url: /workload-integration/
      - title: "Understanding Architecture"
        url: /architecture-diagrams/
  - title: "🔧 Local Development"
    subpages:
      - title: "Project Structure"
        url: /project-structure/
      - title: "Architecture Validation"
        url: /architecture-validation/
      - title: "Security Policy Requirements"
        url: /security-policies/
  - title: "🏢 Advanced Enterprise"
    subpages:
      - title: "Enterprise Architecture"
        url: /enterprise-architecture/
      - title: "Production Deployment"
        url: /enterprise-deployment/
      - title: "Enterprise Integration"
        url: /enterprise-workload-integration/
      - title: "Helm Charts"
        url: /helm-deployment/
      - title: "CRD Requirements"
        url: /enterprise-crd-requirements/

# Social links
github_username: spiffe
repository: spiffe/spire

# SEO settings
google_analytics: 
twitter:
  username: 
  card: summary

# Syntax highlighting
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true