site_name: SPIRE Local Development Environment
site_description: Learn and experiment with SPIFFE/SPIRE on your local machine - perfect for testing, development, and understanding zero-trust identity concepts
site_author: SPIRE Development Community
site_url: https://jfiser247.github.io/spire-dev

repo_name: spiffe/spire-dev
repo_url: https://github.com/spiffe/spire

exclude_docs: |
  venv/

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

nav:
  - 🏠 Home: index.md
  - 🧪 Mermaid Test: test_mermaid.md
  - 🚀 Getting Started:
    - Fresh Install Setup: fresh_install_guide.md
    - Quick Start Integration: quick_start_workload_integration.md
    - Troubleshooting Setup: troubleshooting.md
  - 🎓 Learning SPIRE:
    - SPIFFE Service Integration: spiffe_service_integration_guide.md
    - Workload Integration Guide: workload_integration_guide.md
    - Understanding Architecture: architecture_diagrams.md
  - 🔧 Local Development:
    - Project Structure: project_structure.md
    - Architecture Validation: architecture_validation.md
    - Security Policy Requirements: spire_security_policies.md
  - 🏢 Advanced Enterprise:
    - Enterprise Architecture: enterprise_architecture_diagram.md
    - Production Deployment: enterprise_deployment_guide.md
    - Enterprise Integration: enterprise_workload_integration.md
    - Helm Charts: helm_deployment_guide.md
    - CRD Requirements: enterprise_crd_requirements.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/spiffe/spire
      name: SPIRE on GitHub
    - icon: fontawesome/solid/globe
      link: https://spiffe.io
      name: Learn SPIFFE
    - icon: fontawesome/solid/book
      link: https://spiffe.io/docs/
      name: SPIFFE Documentation
    - icon: fontawesome/brands/slack
      link: https://spiffe.io/community/
      name: Join Community


