apiVersion: v1
kind: ServiceAccount
metadata:
  name: spire-downstream-agent
  namespace: spire-downstream

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spire-downstream-agent-role
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spire-downstream-agent-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spire-downstream-agent-role
subjects:
- kind: ServiceAccount
  name: spire-downstream-agent
  namespace: spire-downstream

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: spire-downstream-agent
  namespace: downstream-workloads

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spire-downstream-agent-workload-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spire-downstream-agent-role
subjects:
- kind: ServiceAccount
  name: spire-downstream-agent
  namespace: downstream-workloads