apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-downstream-controller-manager-config
  namespace: spire-downstream
data:
  controller-manager-config.yaml: |
    apiVersion: spire.spiffe.io/v1alpha1
    kind: ControllerManagerConfig
    metadata:
      name: spire-downstream-controller-manager
      namespace: spire-downstream
    metrics:
      bindAddress: 0.0.0.0:8082
    health:
      healthProbeBindAddress: 0.0.0.0:8083
    leaderElection:
      leaderElect: true
      resourceName: 6be21c33.spiffe.io
      resourceNamespace: spire-downstream
    spireServerSocketPath: /run/spire/sockets/server.sock
    className: spire-downstream
    trustDomain: downstream.example.org
    ignoreNamespaces: ["kube-system", "kube-public", "spire-upstream"]
    clusterSPIFFEIDs:
      default:
        dnsNameTemplates:
          - "{{ .ClusterName }}.{{ .TrustDomain }}"
        federatesWith: ["enterprise-root.org"]
    validatingAdmissionWebhook:
      enabled: true
      failurePolicy: Fail