apiVersion: v1
kind: Service
metadata:
  name: spire-downstream-server
  namespace: spire-downstream
  labels:
    app: spire-downstream-server
spec:
  type: ClusterIP
  ports:
  - name: grpc
    port: 8081
    targetPort: 8081
    protocol: TCP
  - name: health
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: federation
    port: 8443
    targetPort: 8443
    protocol: TCP
  selector:
    app: spire-downstream-server
---
apiVersion: v1
kind: Service
metadata:
  name: spire-downstream-server-external
  namespace: spire-downstream
  labels:
    app: spire-downstream-server
spec:
  type: NodePort
  ports:
  - name: grpc
    port: 8081
    targetPort: 8081
    nodePort: 32081
    protocol: TCP
  - name: federation
    port: 8443
    targetPort: 8443
    nodePort: 32443
    protocol: TCP
  selector:
    app: spire-downstream-server