{{- if and .Values.rbac.create .Values.spireAgent.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "spire.agent.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spire.agent.labels" . | nindent 4 }}
  {{- with .Values.serviceAccountAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "spire.fullname" . }}-agent
  labels:
    {{- include "spire.agent.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods", "nodes", "nodes/proxy"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "spire.fullname" . }}-agent
  labels:
    {{- include "spire.agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "spire.fullname" . }}-agent
subjects:
- kind: ServiceAccount
  name: {{ include "spire.agent.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}