---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    {{- include "spire.labels" . | nindent 4 }}
    name: {{ .Release.Namespace }}
  {{- with .Values.namespaceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: workload
  labels:
    {{- include "spire.labels" . | nindent 4 }}
    name: workload
  {{- with .Values.namespaceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}