{{- if .Values.workloadServices.enabled }}
{{- if .Values.workloadServices.userService.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: workload
  labels:
    {{- include "spire.labels" . | nindent 4 }}
    app.kubernetes.io/component: workload
    app: user-service
spec:
  replicas: {{ .Values.workloadServices.userService.replicas }}
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
      annotations:
        spiffe.io/spiffe-id: {{ .Values.workloadServices.userService.spiffeId | quote }}
    spec:
      serviceAccountName: user-service
      containers:
      - name: user-service
        image: {{ .Values.workloadServices.userService.image }}
        ports:
        - containerPort: 80
        env:
        - name: SPIFFE_ENDPOINT_SOCKET
          value: "unix:///run/spire/sockets/agent.sock"
        volumeMounts:
        - name: spire-agent-socket
          mountPath: /run/spire/sockets
          readOnly: true
      volumes:
      - name: spire-agent-socket
        hostPath:
          path: /run/spire/sockets
          type: Directory
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-service
  namespace: workload
{{- end }}

{{- if .Values.workloadServices.paymentApi.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-api
  namespace: workload
  labels:
    {{- include "spire.labels" . | nindent 4 }}
    app.kubernetes.io/component: workload
    app: payment-api
spec:
  replicas: {{ .Values.workloadServices.paymentApi.replicas }}
  selector:
    matchLabels:
      app: payment-api
  template:
    metadata:
      labels:
        app: payment-api
      annotations:
        spiffe.io/spiffe-id: {{ .Values.workloadServices.paymentApi.spiffeId | quote }}
    spec:
      serviceAccountName: payment-api
      containers:
      - name: payment-api
        image: {{ .Values.workloadServices.paymentApi.image }}
        ports:
        - containerPort: 80
        env:
        - name: SPIFFE_ENDPOINT_SOCKET
          value: "unix:///run/spire/sockets/agent.sock"
        volumeMounts:
        - name: spire-agent-socket
          mountPath: /run/spire/sockets
          readOnly: true
      volumes:
      - name: spire-agent-socket
        hostPath:
          path: /run/spire/sockets
          type: Directory
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-api
  namespace: workload
{{- end }}

{{- if .Values.workloadServices.inventoryService.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: workload
  labels:
    {{- include "spire.labels" . | nindent 4 }}
    app.kubernetes.io/component: workload
    app: inventory-service
spec:
  replicas: {{ .Values.workloadServices.inventoryService.replicas }}
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
      annotations:
        spiffe.io/spiffe-id: {{ .Values.workloadServices.inventoryService.spiffeId | quote }}
    spec:
      serviceAccountName: inventory-service
      containers:
      - name: inventory-service
        image: {{ .Values.workloadServices.inventoryService.image }}
        command: ["python3", "-m", "http.server", "8080"]
        ports:
        - containerPort: 8080
        env:
        - name: SPIFFE_ENDPOINT_SOCKET
          value: "unix:///run/spire/sockets/agent.sock"
        volumeMounts:
        - name: spire-agent-socket
          mountPath: /run/spire/sockets
          readOnly: true
      volumes:
      - name: spire-agent-socket
        hostPath:
          path: /run/spire/sockets
          type: Directory
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory-service
  namespace: workload
{{- end }}
{{- end }}