apiVersion: v1
kind: Service
metadata:
  name: spire-server
  namespace: spire-server
spec:
  selector:
    app: spire-server
  ports:
    - name: server
      port: 8081
      targetPort: 8081
    - name: health
      port: 8080
      targetPort: 8080
    - name: tornjak-backend
      port: 10000
      targetPort: 10000
    - name: tornjak-metrics
      port: 9090
      targetPort: 9090
  type: NodePort
  externalTrafficPolicy: Local
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-bundle
  namespace: spire-server