apiVersion: v1
kind: ConfigMap
metadata:
  name: tornjak-configmap
  namespace: spire-server
data:
  tornjak.conf: |
    server {
      spire_socket_path = "unix:///run/spire/sockets/server.sock"
      spire_config_path = "/run/spire/config/server.conf"
      
      http {
        host = "0.0.0.0"
        port = 10000
        cors {
          enabled = true
        }
      }
    }
    
    plugins {
      DataStore "sql" {
        plugin_data {
          drivername = "sqlite3"
          filename = "/tmp/tornjak.db"
        }
      }
    }