apiVersion: v1
kind: Service
metadata:
  name: tornjak-backend
  namespace: spire-server
  labels:
    app: tornjak-backend
spec:
  type: ClusterIP
  selector:
    app: tornjak-backend
  ports:
  - name: backend-port
    protocol: TCP
    port: 10000
    targetPort: 10000
  - name: metrics-port
    protocol: TCP
    port: 9090
    targetPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: tornjak-backend-nodeport
  namespace: spire-server
  labels:
    app: tornjak-backend
spec:
  type: NodePort
  selector:
    app: tornjak-backend
  ports:
  - name: backend-port
    protocol: TCP
    port: 10000
    targetPort: 10000
    nodePort: 30000