apiVersion: apps/v1
kind: Deployment
metadata:
  name: tornjak-frontend
  namespace: spire-server
  labels:
    app: tornjak-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tornjak-frontend
  template:
    metadata:
      labels:
        app: tornjak-frontend
    spec:
      containers:
      - name: tornjak-frontend
        image: ghcr.io/spiffe/tornjak-frontend:v2.2.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: frontend-port
          containerPort: 3000
          protocol: TCP
        env:
        - name: REACT_APP_API_SERVER_URI
          value: "http://localhost:10000"
        livenessProbe:
          httpGet:
            path: /
            port: frontend-port
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: frontend-port
          initialDelaySeconds: 15
          periodSeconds: 10
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "200m"