apiVersion: apps/v1
kind: Deployment
metadata:
  name: spire-upstream-db
  namespace: spire-upstream
  labels:
    app: spire-upstream-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spire-upstream-db
  template:
    metadata:
      labels:
        app: spire-upstream-db
    spec:
      containers:
      - name: postgres
        image: postgres:13
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: spire
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: spire-upstream-db-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spire-upstream-db-pvc
  namespace: spire-upstream
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: spire-upstream-db
  namespace: spire-upstream
spec:
  selector:
    app: spire-upstream-db
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP