apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spire-upstream-server
  namespace: spire-upstream
  labels:
    app: spire-upstream-server
spec:
  replicas: 1
  serviceName: spire-upstream-server
  selector:
    matchLabels:
      app: spire-upstream-server
  template:
    metadata:
      labels:
        app: spire-upstream-server
    spec:
      serviceAccountName: spire-upstream-server
      shareProcessNamespace: true
      containers:
      - name: spire-server
        image: ghcr.io/spiffe/spire-server:1.9.0
        args:
        - -config
        - /run/spire/config/server.conf
        ports:
        - containerPort: 8081
          name: grpc
        - containerPort: 8080
          name: health
        - containerPort: 8443
          name: federation
        volumeMounts:
        - name: spire-config
          mountPath: /run/spire/config
          readOnly: true
        - name: spire-data
          mountPath: /run/spire/data
        - name: spire-registration-socket
          mountPath: /run/spire/sockets
        livenessProbe:
          httpGet:
            path: /live
            port: 8080
          failureThreshold: 2
          initialDelaySeconds: 15
          periodSeconds: 60
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
      - name: spire-controller-manager
        image: ghcr.io/spiffe/spire-controller-manager:0.4.0
        ports:
        - containerPort: 9443
          name: webhook
        - containerPort: 8082
          name: metrics
        args:
        - --config=controller-manager-config.yaml
        volumeMounts:
        - name: spire-registration-socket
          mountPath: /run/spire/sockets
          readOnly: true
        - name: controller-manager-config
          mountPath: /controller-manager-config.yaml
          subPath: controller-manager-config.yaml
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: spire-config
        configMap:
          name: spire-upstream-server-config
      - name: spire-registration-socket
        emptyDir: {}
      - name: controller-manager-config
        configMap:
          name: spire-upstream-controller-manager-config
  volumeClaimTemplates:
  - metadata:
      name: spire-data
      namespace: spire-upstream
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi