apiVersion: v1
kind: Service
metadata:
  name: spire-upstream-server
  namespace: spire-upstream
  labels:
    app: spire-upstream-server
spec:
  type: ClusterIP
  ports:
  - name: grpc
    port: 8081
    targetPort: 8081
    protocol: TCP
  - name: health
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: federation
    port: 8443
    targetPort: 8443
    protocol: TCP
  selector:
    app: spire-upstream-server
---
apiVersion: v1
kind: Service
metadata:
  name: spire-upstream-server-external
  namespace: spire-upstream
  labels:
    app: spire-upstream-server
spec:
  type: NodePort
  ports:
  - name: grpc
    port: 8081
    targetPort: 8081
    nodePort: 31081
    protocol: TCP
  - name: federation
    port: 8443
    targetPort: 8443
    nodePort: 31443
    protocol: TCP
  selector:
    app: spire-upstream-server